kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/geoipupdate
    dockerfile: geoipupdate/Dockerfile
    context: ./geoipupdate
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest

- name: update
  image: jlesage/drone-push-readme
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/geoipupdate
    readme: geoipupdate/README.md
