kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/openalpr
    dockerfile: openalpr/Dockerfile
    context: ./openalpr
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest

- name: update
  image: misotolar/dockerhub-update
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/openalpr
    readme: openalpr/README.md
    desc: "OpenALPR Ubuntu LTS image"
