kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:

- name: clone
  image: alpine/git
  commands:
  - git init --quiet
  - git remote add origin $DRONE_REMOTE_URL
  - git fetch --quiet --depth=1 origin "+refs/heads/$DRONE_BRANCH:"
  - git checkout $DRONE_COMMIT -b $DRONE_BRANCH

- name: publish
  image: misotolar/drone-docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/repman
    dockerfile: repman/Dockerfile
    cache_from: misotolar/repman:latest
    context: ./repman
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest

- name: update
  image: misotolar/drone-docker-update
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/repman
    readme: repman/README.md
    desc: "Repman Alpine FPM image"