kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/dockerhub-update
    dockerfile: dockerhub-update/Dockerfile
    context: ./dockerhub-update
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest

- name: update
  image: misotolar/dockerhub-update
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/dockerhub-update
    readme: dockerhub-update/README.md
    desc: "Docker Hub repository update"
