kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/phppgadmin
    dockerfile: phppgadmin/Dockerfile
    context: ./phppgadmin
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest

- name: update
  image: misotolar/dockerhub-update
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/phppgadmin
    readme: phppgadmin/README.md
    desc: "phpPgAdmin Alpine FPM image"