kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/php7.1-fpm-bionic
    dockerfile: php7.1-fpm-bionic/Dockerfile
    context: ./php7.1-fpm-bionic
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
