kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:

- name: clone
  image: alpine/git
  commands:
  - git init --quiet
  - git remote add origin $DRONE_REMOTE_URL
  - git fetch --quiet --depth=1 origin "+refs/heads/$DRONE_BRANCH:"
  - git checkout $DRONE_COMMIT -b $DRONE_BRANCH

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/php7.1-fpm-bionic
    dockerfile: php7.1-fpm-bionic/Dockerfile
    context: ./php7.1-fpm-bionic
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest

- name: update
  image: misotolar/dockerhub-update
  settings: 
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/php7.1-fpm-bionic
    readme: php7.1-fpm-bionic/README.md
    desc: "PHP 7.1 Ubuntu Bionic development FPM image"
