kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: misotolar/php7.4-fpm-buster
    dockerfile: php7.4-fpm-buster/Dockerfile
    context: ./php7.4-fpm-buster
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
